"use client";

import { useState } from "react";
import {
  Accordion, AccordionItem, Badge, Breadcrumbs, Button, Card, CardContent, CardHeader, CardTitle, Checkbox, Container, CountUp, Dialog, EmptyState, ErrorState, FormField, Input, Pagination, Radio, Reveal, Section, SectionHeading, Select, Sheet, Skeleton, Stat, Stepper, Switch, Tabs, Textarea, Toast, ToastViewport, Tooltip,
} from "@/components/ui";

function ComponentSet({ theme }: { theme: "light" | "dark" }) {
  const [dialogOpen, setDialogOpen] = useState(false);
  const [sheetOpen, setSheetOpen] = useState(false);
  const [toastVisible, setToastVisible] = useState(true);
  const [page, setPage] = useState(2);
  return <div data-theme={theme} className="min-h-screen bg-bg text-ink"><Container><Section className="space-y-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-brand-deep">{theme} theme</p><h1 className="mt-2 text-4xl font-semibold">Design system</h1><p className="mt-3 max-w-2xl text-ink-muted">Accessible primitives for Vakratund Construction. Tab through controls to inspect focus states.</p></div><Badge variant="brand">Phase 2</Badge></div>

      <div className="space-y-6"><SectionHeading eyebrow="Foundations" title="Tokens, type and status" description="Semantic classes stay stable while the light and dark values change." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Since" value={<CountUp value={2003} />} detail="Established" /><Stat label="Projects" value="40+" detail="Construction and repair" /><Stat label="Status" value={<Badge variant="success">Ready</Badge>} detail="Accessible defaults" /><Stat label="Accent" value={<span className="text-brand-deep">Brand deep</span>} detail="Text-safe accent" /></div></div>

      <div className="space-y-6"><SectionHeading eyebrow="Actions" title="Buttons and badges" /><div className="flex flex-wrap items-center gap-3"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="link">Link</Button><Button size="sm">Small</Button><Button size="lg">Large</Button><Button loading>Loading</Button><Button disabled>Disabled</Button></div><div className="flex flex-wrap gap-2"><Badge>Neutral</Badge><Badge variant="brand">Brand</Badge><Badge variant="success">Success</Badge><Badge variant="warning">Warning</Badge><Badge variant="danger">Danger</Badge></div></div>

      <div className="grid gap-8 lg:grid-cols-2"><div className="space-y-5"><SectionHeading eyebrow="Forms" title="Inputs and validation" /><FormField label="Full name" htmlFor={`${theme}-name`} required hint="Use the name shared with your enquiry."><Input id={`${theme}-name`} placeholder="Engr. Salil Chawan" /></FormField><FormField label="Email" htmlFor={`${theme}-email`} error="Enter a valid email address."><Input id={`${theme}-email`} type="email" aria-invalid="true" placeholder="name@example.com" /></FormField><FormField label="Service" htmlFor={`${theme}-service`}><Select id={`${theme}-service`} defaultValue=""><option value="" disabled>Select a service</option><option>Structural repairs</option><option>Waterproofing</option></Select></FormField><FormField label="Requirements" htmlFor={`${theme}-requirements`}><Textarea id={`${theme}-requirements`} placeholder="Tell us about the project" /></FormField><div className="flex flex-wrap gap-5"><label className="flex items-center gap-2"><Checkbox defaultChecked /> Consent given</label><label className="flex items-center gap-2"><Radio name={`${theme}-choice`} defaultChecked /> Residential</label><label className="flex items-center gap-2"><Radio name={`${theme}-choice`} /> Commercial</label></div><Switch label="Send project updates" defaultChecked /></div><Card><CardHeader><CardTitle>Form states</CardTitle></CardHeader><CardContent className="space-y-4"><p>All controls have visible labels, a minimum touch target, and a brand-deep focus ring.</p><div className="flex gap-3"><Input disabled value="Disabled input" readOnly /><Input aria-invalid="true" value="Error input" readOnly /></div></CardContent></Card></div>

      <div className="space-y-6"><SectionHeading eyebrow="Content" title="Cards, navigation and disclosure" /><Card><CardHeader><CardTitle>Project management</CardTitle></CardHeader><CardContent>PMC and turnkey project development for societies and individual property owners.</CardContent></Card><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Services", href: "/services" }, { label: "Structural repairs" }]} /><Tabs tabs={[{ id: "overview", label: "Overview", content: <p className="text-ink-muted">A tab panel with keyboard-focusable content.</p> }, { id: "scope", label: "Scope", content: <p className="text-ink-muted">Survey, plan, execute and hand over.</p> }, { id: "disabled", label: "Disabled", content: null, disabled: true }]} /><Accordion><AccordionItem title="What is a structural audit?" defaultOpen>A structured review of an RCC building to identify defects and recommend action.</AccordionItem><AccordionItem title="Do you serve housing societies?">Yes. Vakratund works with co-operative housing societies in Thane and Mumbai.</AccordionItem></Accordion></div>

      <div className="space-y-6"><SectionHeading eyebrow="Feedback" title="Dialogs, feedback and loading" /><div className="flex flex-wrap gap-3"><Button onClick={() => setDialogOpen(true)}>Open dialog</Button><Button variant="secondary" onClick={() => setSheetOpen(true)}>Open sheet</Button><Tooltip label="Helpful context"><Button variant="ghost" aria-label="More information">Hover or focus me</Button></Tooltip></div><div className="grid gap-4 md:grid-cols-3"><Skeleton className="h-24" /><EmptyState title="No projects yet" description="Published projects will appear here." /><ErrorState description="The preview data could not be loaded." /></div><div className="rounded-card border p-5"><Stepper currentStep={1} steps={[{ label: "Service" }, { label: "Details" }, { label: "Estimate" }, { label: "Contact" }]} /></div><Pagination page={page} pageCount={4} onPageChange={setPage} /><div className="flex justify-center"><Button variant="secondary" onClick={() => setToastVisible(true)}>Show toast</Button></div><Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} title="Request a quote" description="This is a native dialog with Escape-to-close support."><p className="text-ink-muted">Share a few project details and the team will follow up.</p><Button onClick={() => setDialogOpen(false)}>Continue</Button></Dialog><Sheet open={sheetOpen} onClose={() => setSheetOpen(false)} title="Mobile summary"><p className="text-ink-muted">The sheet uses the same accessible dialog foundation.</p></Sheet></div>

      <div className="space-y-6"><SectionHeading eyebrow="Motion" title="Reduced-motion aware" /><Reveal><Card><CardContent>Reveal animates opacity and position once. CountUp animates only when motion is allowed: <strong className="text-ink"><CountUp value={2003} /></strong>.</CardContent></Card></Reveal></div>
    </Section></Container>{toastVisible ? <ToastViewport><Toast title="Design system loaded" variant="success" onDismiss={() => setToastVisible(false)}>All sample components are available.</Toast></ToastViewport> : null}</div>;
}

export function DesignSystemShowcase() {
  return <main><ComponentSet theme="light" /><ComponentSet theme="dark" /></main>;
}
